# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer01.sparx.com:
  peer0.private.sparx.com:
  peer1.private.sparx.com:

networks:
  sparx:

services:

  orderer01.sparx.com:
    container_name: orderer01.sparx.com
    image: hyperledger/fabric-orderer:2.2.4
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=8051
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/keystore/priv_key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/signcerts/cert.pem
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/tlscacerts/tls-localhost-8054-ca-orderer.pem]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/signcerts/cert.pem
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/keystore/priv_key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/tlscacerts/tls-localhost-8054-ca-orderer.pem]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
        - ../network/ordererOrganizations/sparx.com/system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../network/ordererOrganizations/sparx.com/orderers/orderer01.sparx.com/msp:/var/hyperledger/orderer/msp
        - ../network/ordererOrganizations/sparx.com/orderers/orderer01.sparx.com/tls:/var/hyperledger/orderer/tls
        - orderer01.sparx.com:/var/hyperledger/production/orderer
    ports:
      - 8051:8051
    networks:
      - sparx

  peer0.private.sparx.com:
    container_name: peer0.private.sparx.com
    image: hyperledger/fabric-peer:2.2.4
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=compose-files_sparx
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/keystore/priv_key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/tlscacerts/tls-localhost-7054-ca-sparx.pem
      # Peer specific variabes
      - CORE_PEER_ID=peer0.private.sparx.com
      - CORE_PEER_ADDRESS=peer0.private.sparx.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.private.sparx.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.private.sparx.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.private.sparx.com:7051
      - CORE_PEER_LOCALMSPID=SparxMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    volumes:
        - /var/run/:/host/var/run/
        - ../network/peerOrganizations/private.sparx.com/peers/peer0.private.sparx.com/msp:/etc/hyperledger/fabric/msp
        - ../network/peerOrganizations/private.sparx.com/peers/peer0.private.sparx.com/tls:/etc/hyperledger/fabric/tls
        - peer0.private.sparx.com:/var/hyperledger/production
        - ../network/peerOrganizations/private.sparx.com/peers/peer0.private.sparx.com/conf/core.yaml:/etc/hyperledger/fabric/core.yaml
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
    networks:
      - sparx

  peer1.private.sparx.com:
    container_name: peer1.private.sparx.com
    image: hyperledger/fabric-peer:2.2.4
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=compose-files_sparx
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/keystore/priv_key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/tlscacerts/tls-localhost-7054-ca-sparx.pem
      # Peer specific variabes
      - CORE_PEER_ID=peer1.private.sparx.com
      - CORE_PEER_ADDRESS=peer1.private.sparx.com:7151
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7151
      - CORE_PEER_CHAINCODEADDRESS=peer1.private.sparx.com:7152
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7152
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.private.sparx.com:7151
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.private.sparx.com:7151
      - CORE_PEER_LOCALMSPID=SparxMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    volumes:
        - /var/run/:/host/var/run/
        - ../network/peerOrganizations/private.sparx.com/peers/peer1.private.sparx.com/msp:/etc/hyperledger/fabric/msp
        - ../network/peerOrganizations/private.sparx.com/peers/peer1.private.sparx.com/tls:/etc/hyperledger/fabric/tls
        - peer1.private.sparx.com:/var/hyperledger/production
        - ../network/peerOrganizations/private.sparx.com/peers/peer1.private.sparx.com/conf/core.yaml:/etc/hyperledger/fabric/core.yaml
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7151:7151
    networks:
      - sparx
